theme: jekyll-theme-cayman
title: Bethel Melesse Tessema
description: Masters student in AI at Ajou University, South Korea. Interested in generalization of Transformer models to low-resource tasks. Long-term resident of Korea with F2-7 visa. Download my [Resume](https://github.com/bethelmelesse/bethelmelesse.github.io/raw/main/Bethel_Melesse_Resume.pdf)!
