theme: jekyll-theme-cayman
title: Bethel Melesse's Homepage
description: Master's student in AI at Ajou University, South Korea. Interested in generalization of Transformer models to low-resource tasks. Long-term resident of Korea with F2-7 visa.
